inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4.1
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - '**/Gemfile'
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*
    - config/environments/*
    - config/initializers/*
    - db/seeds.rb
    - spec/support/helpers/capybara.rb
    - spec/rails_helper.rb
Metrics/BlockLength:
  Exclude:
    - 'app/admin/*.rb'
    - 'spec/factories/*.rb'
    - 'spec/controllers/*.rb'
    - 'spec/features/**/*.rb'
    - 'spec/rails_helper.rb'
